### ISSUE TITLE
Can't decrypt the enckey after upgrading to 2.9.x

### ISSUE THREAD

**Issue by SherifNagy** [privacyidea/privacyideaadm#16]
I just updated to the 2.9.x from 2.8.x on a Debian environment, I had the enckey already encrypted with the security module, after the update whenever I run the commands for the securitymodule to decrypt the key I get the following error:

<pre>
Please enter password for 'admin':
Traceback (most recent call last):
  File "/usr/bin/privacyidea", line 1467, in <module>
    main()
  File "/usr/bin/privacyidea", line 1462, in main
    no_ssl_check=args.nosslcheck)
  File "/usr/lib/python2.7/dist-packages/privacyideautils/clientutils.py", line 96, in __init__
    self.set_credentials(username, password)
  File "/usr/lib/python2.7/dist-packages/privacyideautils/clientutils.py", line 129, in set_credentials
    raise Exception("Invalid Credentials: %s" % r.status_code)
Exception: Invalid Credentials: 400
</pre>

- I am using stable release of privacyIDEA and privacyIDEA Admin
- LDAP for the users and local for the admin
- I have a 2nd machine still on 2.8.x and it is working fine
- enckey and pi.cfg did not change on both machines " they are identical

**Comment by cornelinux** [comment]
After investigating this, it turns out, that this is an issue of the server. So we continue working with privacyidea/privacyidea#304 and close this issue.
