### ISSUE TITLE
Introduce command line parameters to unlock and lock YubiKeys

### ISSUE THREAD

**Issue by berndnicklas** [privacyidea/privacyideaadm#23]
Hello Cornelius,

for more easy YubiKey rollout with privacyideaadm we were pleased about the ability to

- unlock YubiKey slot via a additional command line parameter (e.g.  --yubiunlockpass=..., --yubiunlockpasslist=...). Of course, in reality, it is possible that over the time you have many YubiKeys in production with different lock passwords, that's why a password list would be great.
- remove lock for YubiKey slot via additional command line parameter (e.g. --yubiremovelock)
- lock YubiKey slot with password (e. g. --yubilockpass=...)

It would be great, it the lock/unlock passwords could be read from a seperate file (for security reasons).

Best regards,

Bernd

**Comment by cornelinux** [comment]
The privacyIDEA command line client can take every parameter from a file when specifying the file as @file:

    privacyidea @all_the_secrets <other parameters>

Does this sound sensible to you?
In my opinion there is no additional file needed.

**Comment by berndnicklas** [comment]
Yes, this would be perfect.
