### ISSUE TITLE
Statistics in WebUI should be limited to the user accessing the statistics

### ISSUE THREAD

**Issue by berndnicklas** [privacyidea/privacyideaadm#24]
Hello,

ordinary users in WebUI actually have access to the statistics (graphs) over all users, including sensible information like username and token serial numbers, which should be fixed for compliance with security and privacy regulations. So at least for ordinary users, statistics should be limited to the user accessing the statistics.

Our work-around right now is to disable statistics (/audit/statistics) completely via web server rules.

Best regards,

Bernd

**Comment by cornelinux** [comment]
Thanks for reporting. Please put this to the project privacyidea/privacyidea ;-)
not admin client...

**Comment by cornelinux** [comment]
Another workaround is, to disable "auditlog" right for the users in the user policy.
I think we will not allow statistics for the user anyway.
