### ISSUE TITLE
Add enrollment of ssh keys on yubikeys

### ISSUE THREAD

**Issue by cornelinux** [privacyidea/privacyideaadm#41]
The yubikey (or nitrokey) can be used to store ssh keys.

We should add the possibility to gernerate a key pair on the yubikey and register it as ssh key on the privacyIDEA server.
A command could look like this:

    privacyidea token yubikey_register_sshkey

# Todos:

* Create a specification

* We need to specifiy the parameters, that could be passed in the command like 
  * key size
  * username
  * key comment...
  * ...

* We should check, if we could define "policies" on the server, which are fetched prior of enrollment.
  On the other hand the admin with the command line client could override the policies anyways.

**Comment by cornelinux** [comment]
I think this is obsolete with allowing to enroll certificates on the yubikey. These can be used and converted to SSH keys and used for login via SSH.

**Comment by plettich** [comment]
I know that GPG-Keys can be used to derive a SSH-Key but Certificates as well?

**Comment by cornelinux** [comment]
Yes you can. I actually opened an issue for it a while ago:
https://github.com/privacyidea/privacyidea/issues/2052

The goal is to improve the process of certificate creation. PIV allows attestation, i.e. the backend can verify that the keys were generated on the smartcard. This is an important aspect, that was missing in the past.

Using the PIV smartcard and certificates, we can do everything:
* ssh login
* local login with certificates
* SSL
* SMIME...
