### ISSUE TITLE
Rename SafeConfigParser to ConfigParser

### ISSUE THREAD

**Issue by laclaro** [privacyidea/privacyideaadm#48]
Pycharm brought this up.

SafeConfigParser has been renamed to ConfigParser. We should change the line:

https://github.com/privacyidea/privacyideaadm/blob/master/scripts/privacyidea#L285

**Comment by cornelinux** [comment]
The config parser was not used and is removed in my PR #47.
@laclaro  So if you do not reject, I would ask you to close this again.
